name: e2e-tests-cypress
on: [push]
jobs:
  cypress-run-letGo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start